---
- name: Install Docker on Rocky Linux
  hosts: all
  become: true


  tasks:

    - name: Installazione pacchetti necessari
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Aggiunta della repository di Docker
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Installazione dei packages di Docker 
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Inizializzazione e abilitazione di Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Aggiunta dell'utente vagrant al gruppo docker
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Installazione immagine Jenkins
      command: docker pull jenkins/jenkins:lts

    - name: controllo installazione pip
      package:
        name: python3-pip
        state: present

    - name: controllo installazione del modulo 'requests'
      pip:
        name: requests
        executable: pip3 

    - name: creazione di una rete Docker con IP statico 
      community.docker.docker_network:
        name: jenkins-net
        driver: bridge
        ipam_config:
          - subnet: 172.18.0.0/16
            gateway: 172.18.0.1


    - name: Avvio container Jenkins master con IP statico
      community.docker.docker_container:
        name: jenkins-master
        image: jenkins/jenkins:lts
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - jenkins_home:/var/jenkins_home
          - /usr/bin/docker:/usr/bin/docker
          - /var/run/docker.sock:/var/run/docker.sock 

        networks:
          - name: jenkins-net
            ipv4_address: 172.18.0.10
        detach: true
 


    - name: Scarica immagine jenkins/inbound-agent
      community.docker.docker_image:
        name: jenkins/inbound-agent
        source: pull

    - name: Avvio container Jenkins agent
      community.docker.docker_container:
        name: jenkins-agent1
        image: jenkins/inbound-agent
        state: started
        restart_policy: unless-stopped
        env:
          JENKINS_URL: http://172.18.0.10:8080
          JENKINS_AGENT_NAME: agent1
          JENKINS_AGENT_WORKDIR: /home/jenkins/agent
          JENKINS_SECRET: fb580259a7f0476443bcffe6613b1359daf3e81a2e793a67c79b28db30f37040 


        networks:
          - name: jenkins-net
        detach: true
#Fine step 1

