apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{.Values.namespace}}
  labels:
    {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ .Values.appName }}
