pipeline {
    agent { label 'master' }

    environment {
        IMAGE_NAME = 'flask-page'
    }

    stages {
        stage('Check Branch') {
            steps {
                script {
                    def branch = sh(script: "git rev-parse --abbrev-ref HEAD", returnStdout: true).trim()

                    if (branch == "main") {
                        env.IMAGE_TAG = "latest"
                    } else if (branch == "develop") {
                        def sha = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                        env.IMAGE_TAG = "develop-${sha}"
                    } else {
                        env.IMAGE_TAG = branch
                    }

                    echo "Branch: ${branch}"
                    echo "Docker Tag: ${env.IMAGE_TAG}"
                }
            }
        }

        stage('check git tag'){

            steps {
                script {
                    try {
                        def gitTag = sh(script: "git describe --contains --tags \$(git rev-parse HEAD)", returnStdout: true).trim()
                        if (gitTag) {
                            env.IMAGE_TAG = gitTag
                            echo "Found Git tag: ${gitTag}"
                        } else {
                            echo "No tag found on this commit."
                        }
                    } catch (err) {
                        echo "Error running git describe: ${err}"
                        // fallback o azione alternativa, ad esempio lasciare IMAGE_TAG vuota o impostare un valore default
                        env.IMAGE_TAG = ''
                    }
                }
            }

        }

        stage('Build') {
            steps {
                sh "docker build -t ${env.IMAGE_NAME}:${env.IMAGE_TAG} ."
            }
        }

        stage('Push') {
            steps {
                sh "docker push accountaziendale/${env.IMAGE_NAME}:${env.IMAGE_TAG}"
            }
        }
    }
}
